### ISSUE TITLE
VMware Controller: In the UI "BSS_USER_ID" , "BSS_USER_KEY","BSS_USER_PASSWORD" is missing

### ISSUE THREAD

**Issue by elfriedegoetz** [servicecatalog/oscm#122]
[Build]
docker 17.7 2018/07/17

[Steps to reproduce]
login to APP and set ORGANISATION_ID for vmware controller to "ORG_Technical Provider"
[Expected result]
it is possible to login to vmware controller
[Observed result]
it is not possible
[Detail]
VMware Controller: In the UI "BSS_USER_ID" , "BSS_USER_KEY","BSS_USER_PASSWORD" is missing
Additionally the administrator has no access to the controller

**Comment by GoebelL** [comment]
This is addressed in https://github.com/servicecatalog/oscm/pull/139

**Comment by GoebelL** [comment]
@elfriedegoetz 
Please verify after PR#139 is merged.

**Comment by kowalczyka** [comment]
Issue is resolved with 34cefdd

**Comment by elfriedegoetz** [comment]
It is still not possible to change the Controler_org_ID.
step1 : login to oscm-app
step2: change ContolerID ess.vmware to "TP1"
step3: click save
step4: log in to vmware controller: oscm-app-vmvare
--> not possible neither with "administrator" nor with "TP1"

The I tested the following:
step1: first log in to vmware controller: oscm-app-vmvare 
step2: change BSS_UESR_ID and BSS_USER_KEY and BSS_USER_PASSWORD
step3: click save
step4: log in to APP: oscm-app
--> not possible. Error occurs
![vmware](https://user-images.githubusercontent.com/15209605/44392495-9fa2e200-a532-11e8-9eb4-6a84fff42288.PNG)

**Comment by GoebelL** [comment]
Why do you want to change the controller ID ? The ID must not be changed. It has to match the JNDI name of the controller service. 
You are probably mixing it with organization ID, or?

**Comment by GoebelL** [comment]
The given steps are not useful.

**Comment by elfriedegoetz** [comment]
Of course I do not mean controller ID  but organization ID , sorry.

It is still not possible to change the organisation ID for the controller.
 step1 : login to APP
 step2: change Organization ID for controller ess.vmware:  TP1
 step3: click save
 step4: log in to vmware Controller

 --> not possible neither with "administrator" nor with "TP1"

note:
It is not always reproducible. see issue 100.

**Comment by kowalczyka** [comment]
Organization ID is generated when creating new organization. 

TP1 which you are using here is probably username of that organization. Please find the organization id in the UI of oscm-core and try to use it.

**Comment by elfriedegoetz** [comment]
I'm sorry, that was my mistake. I have now tested with the correct organization ID.
Now it works. 
 step1 : login to APP
 step2: change Organization ID for controller ess.vmware: "c913f6e3"
 step3: click save
 step4: log in to vmware Controller with administrator from Organisation "c913f6e3"
 step5: make changes for BSS_USER
 step6. click save
 step7: login again with BSS_USER
