### ISSUE TITLE
VMware : Details Information will not be updated

### ISSUE THREAD

**Issue by elfriedegoetz** [servicecatalog/oscm#162]
[Build]
docker 17.7 2018/10/17

[Steps to reproduce]
create a VMware instance
goto My Subscrption
stop the Instance

[Expected result]
The Details Information  will be updated

[Observed result]
status is still running 

ACCOUNT-> view operations: the stop operation is completed and the Instance has stopped

**Comment by GoebelL** [comment]
Same as #152. Apparently caused by missing progress callback from APP. This should be fixed together.

**Comment by elfriedegoetz** [comment]
update detail information after start/stop still not work for vmware. Azure and aws work fine

**Comment by elfriedegoetz** [comment]
the status tab works fine therefore I close the bug again.
