### ISSUE TITLE
changing controller settings results in java.lang.reflect.UndeclaredThrowableException

### ISSUE THREAD

**Issue by ghost** [servicecatalog/oscm#34]
[Build] 17.5 2017/11/07

[Steps to reproduce]
1. log in to aws controller as administrator (who is also technology provider and service manager)
2. change UserID, key and password   
3. save configuration

[Expected result]
readable exception

[Observed result]
java.lang.reflect.UndeclaredThrowableException

[Details]
This step is necessary to update the controller manager.

**Comment by ghost** [comment]
This is extremely annoying, since I do not know what the problem is. I changed the password only and I get this message. I have no idea if the change was commited or not.

**Comment by grubskim** [comment]
I am not getting this exception. Could you please retest with the changes i pushed today regarding platform operator login to APP?

**Comment by ghost** [comment]
administrator login to controller works (so I guess I am using the correct version); And I am still getting this exception. e.g. Changing password (to a different value) results in this exception

**Comment by grubskim** [comment]
I can reproduce it now.

**Comment by grubskim** [comment]
Removed authentication with Bes during DB operation in APP controller. I think it is unnecessary to communicate with BES when saving/retrieving from APP db.
